name: Insights Core Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [2.7, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: flake8
      run: |
        pip install -e .[linting]
        flake8 .
    - name: pytest
      run: |
        pip install -e .[testing]
        pytest

  python26-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python-2.6
      run: |
        sudo apt-get install build-essential
        wget https://www.python.org/ftp/python/2.6.7/Python-2.6.7.tgz
        tar -zxvf Python-2.6.7.tgz
        cd ./Python-2.6.7
        ./configure --prefix=/python2 && make && make install
    - name: flake8
      run: |
        ./python2/bin/python2.6 -m pip install -e .[linting]
        ./python2/bin/python2.6 -m flake8 .
    - name: pytest
      run: |
        ./python2/bin/python2.6 -m pip install -e .[testing]
        ./python2/bin/python2.6 -m pytest

  docs-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install dependencies
      run: |
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
    - name: docs Test
      run: |
        pip install docutils==0.17
        pip install -e .[docs]
        sphinx-build -W -b html -qa -E docs docs/_build/html
