name: Insights Core Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [2.7, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install dependencies
      run: |
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
    - name: flake8
      run: |
        pip install -e .[linting]
        flake8 .
    - name: pytest
      run: |
        pip install -e .[testing]
        pytest
    - name: docs Test
      run: |
        pip install -e .[docs]
        sphinx-build -W -b html -qa -E docs docs/_build/html
